/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.view;

import br.com.fatec.Enum.EnumTipoConta;

/**
 *
 * @author aluno
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public FrmMenu(EnumTipoConta tipo){
        this();
        System.out.println(tipo);
        if (EnumTipoConta.secretaria.equals(tipo)){
            //bloqueia botões de veterinario
            pesquisarConsultaVet.setVisible(false);
            controleContas.setVisible(false);
        }else if (EnumTipoConta.veterinario.equals(tipo)){
            menuVeterinario.setVisible(false);
            menuAnimal.setVisible(false);
            menuCliente.setVisible(false);
            agendarConsulta.setVisible(false);
            pesquisarConsultaSec.setVisible(false);
            controleContas.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAnimal = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        pesquisarConsultaVet = new javax.swing.JMenuItem();
        agendarConsulta = new javax.swing.JMenuItem();
        pesquisarConsultaSec = new javax.swing.JMenuItem();
        menuVeterinario = new javax.swing.JMenu();
        cadastroVeterinario = new javax.swing.JMenuItem();
        Historico = new javax.swing.JMenu();
        gerarHistorico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        controleContas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem1);

        jMenuBar1.add(menuCliente);

        menuAnimal.setText("Animal");
        menuAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnimalActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Animal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAnimal.add(jMenuItem2);

        jMenuBar1.add(menuAnimal);

        menuConsulta.setText("Consulta");

        pesquisarConsultaVet.setText("Pesquisar");
        pesquisarConsultaVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarConsultaVetActionPerformed(evt);
            }
        });
        menuConsulta.add(pesquisarConsultaVet);

        agendarConsulta.setText("Agendar");
        agendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarConsultaActionPerformed(evt);
            }
        });
        menuConsulta.add(agendarConsulta);

        pesquisarConsultaSec.setText("Pesquisar");
        pesquisarConsultaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarConsultaSecActionPerformed(evt);
            }
        });
        menuConsulta.add(pesquisarConsultaSec);

        jMenuBar1.add(menuConsulta);

        menuVeterinario.setText("Veterinario");

        cadastroVeterinario.setText("Cadastrar");
        cadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVeterinarioActionPerformed(evt);
            }
        });
        menuVeterinario.add(cadastroVeterinario);

        jMenuBar1.add(menuVeterinario);

        Historico.setText("Historico");
        Historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricoActionPerformed(evt);
            }
        });

        gerarHistorico.setText("Gerar Historico");
        gerarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarHistoricoActionPerformed(evt);
            }
        });
        Historico.add(gerarHistorico);

        jMenuBar1.add(Historico);

        jMenu1.setText("Conta");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        controleContas.setText("Controle de Contas");
        controleContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controleContasActionPerformed(evt);
            }
        });
        jMenu1.add(controleContas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnimalActionPerformed
        
    }//GEN-LAST:event_menuAnimalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmCliente frame = new FrmCliente();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmAnimal frame = new FrmAnimal(null);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void agendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarConsultaActionPerformed
        FrmAgendamento frame = new FrmAgendamento();
        frame.setVisible(true);
    }//GEN-LAST:event_agendarConsultaActionPerformed

    private void pesquisarConsultaVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarConsultaVetActionPerformed
        FrmConsultarAgenVet frame = new FrmConsultarAgenVet();
        frame.setVisible(true);
    }//GEN-LAST:event_pesquisarConsultaVetActionPerformed

    private void cadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVeterinarioActionPerformed
        FrmCadastroVet frame = new FrmCadastroVet();
        frame.setVisible(true);
    }//GEN-LAST:event_cadastroVeterinarioActionPerformed

    private void pesquisarConsultaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarConsultaSecActionPerformed
        FrmConsultarAgendamento frame = new FrmConsultarAgendamento();
        frame.setVisible(true);
    }//GEN-LAST:event_pesquisarConsultaSecActionPerformed

    private void HistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricoActionPerformed
       
    }//GEN-LAST:event_HistoricoActionPerformed

    private void gerarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarHistoricoActionPerformed
        FrmHistorico hist = new FrmHistorico();
        hist.setVisible(true);
    }//GEN-LAST:event_gerarHistoricoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        FrmControleContas frm = new FrmControleContas();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void controleContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controleContasActionPerformed
       FrmControleContas frame = new FrmControleContas();
       frame.setVisible(true);
    }//GEN-LAST:event_controleContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Historico;
    private javax.swing.JMenuItem agendarConsulta;
    private javax.swing.JMenuItem cadastroVeterinario;
    private javax.swing.JMenuItem controleContas;
    private javax.swing.JMenuItem gerarHistorico;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu menuAnimal;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuVeterinario;
    private javax.swing.JMenuItem pesquisarConsultaSec;
    private javax.swing.JMenuItem pesquisarConsultaVet;
    // End of variables declaration//GEN-END:variables
}
